name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build Site
        run: bash scripts/build_site.sh

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site
          umbrella-dir: pr-preview
          action: auto
