name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rossjrw/pr-preview-action@v1
        with:
          source_dir: .
          wait-for-pages-deployment: true
          umbrella-dir: pr-preview
